### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by JosephWoodward** [JosephWoodward/SlugityDotNet#2]

**Comment by ctolkien** [comment]
I can tackle this, as I've done it for a number of other packages. Just checking that this repo is being maintained?

**Comment by JosephWoodward** [comment]
@ctolkien That would be great! In fact I've already started converting it to .NET Standard (see this branch https://github.com/JosephWoodward/SlugityDotNet/tree/NetStandardUpdate), though I've hit a snag with an API that's been changed and not been able to find where it's gone.

**Comment by ctolkien** [comment]
Would that API happen to be `ToTitleCase`?

Doesn't exist in .Net Core.... Hit the same issue.

**Comment by JosephWoodward** [comment]
Alright, I did begin to wonder. It looks like we'll have implement our own version and use a compiler directive to switch between the two depending on the platform.

**Comment by ctolkien** [comment]
I would probably look at how Humanizer (https://github.com/Humanizr/Humanizer)  handles it  as they have .Net Core support and a TitleCase method. They are MIT as well, so no major licensing hurldes that I'm aware of.

Could always take a dependency on that lib too just for .Net Core, but it seems a bit much to support one small feature.

**Comment by JosephWoodward** [comment]
Given it's just a method, I think it would be best not to take a dependency on an external library, and rather opt to create a replacement `ToTitleCase` method. Thoughts?

**Comment by ctolkien** [comment]
Yeah agreed.

Here's how humanizer do it:

https://github.com/Humanizr/Humanizer/blob/dev/src/Humanizer/Transformer/ToTitleCase.cs#L9

**Comment by JosephWoodward** [comment]
Oh cool, I think we should go with this then and change it to suit our needs. Probably best we give credit in the code in the form of comment highlighting where it came from?

**Comment by JosephWoodward** [comment]
As this thread has been quiet for a few days I decided to implement it. I hope that's ok. Thank you for pointing me in the direction of Humanizr too!

**Comment by ctolkien** [comment]
Yep, all good. With the announcement of NetStandard2, it sounds like some of these API's will be making a return as well.
